### ISSUE TITLE
перенести новость в блог (спортивное программирование) [0.5h]

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#158]
https://odin.mgimo.ru/nov-pod-mgimo/3477-student-mgimo-odintsovo-prinyal-uchastie-v-sborakh-po-sportivnomu-programmirovaniyu

Комментарии:
- определить год в дате, использовать во front matter в блоге
- футер новости - Оригинал на сайте МГИМО-Одинцово <ссылка>
- текст новости показать здесь в ишью в верстке
- прогнать через `npx prettier`
- PR в ветку preview, референсить ишью в коммитах и в PR

**Comment by Ks-Roman** [comment]
I'm going to make it

**Comment by epogrebnyak** [comment]
> I'm going to make it
> ### [Студент МГИМО-Одинцово принял участие в сборах по спортивному программированию](https://odin.mgimo.ru/nov-pod-mgimo/3477-student-mgimo-odintsovo-prinyal-uchastie-v-sborakh-po-sportivnomu-programmirovaniyu)

@Ks-Roman  - any progress?

**Comment by Ks-Roman** [comment]
привет, прогресса нет01.07.2022, 15:29, "Evgeny Pogrebnyak" ***@***.***>:

I'm going to make it
Студент МГИМО-Одинцово принял участие в сборах по спортивному программированию

@Ks-Roman  - any progress?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
-- С УважениемРоманЗарабатывайте или поручите рутинную работу https://work-zilla.com/?ref=2169210
